version: 1
update_configs:
  - package_manager: "javascript"
    # Disable dependabot
    open-pull-requests-limit: 0
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
    - match:
        update_type: "semver:minor"
  - package_manager: "ruby:bundler"
    # Disable dependabot
    open-pull-requests-limit: 0
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
    - match:
        update_type: "semver:minor"
